### ISSUE TITLE
在按钮的回调中立即finish activity在部分手机上回直接崩溃

### ISSUE THREAD

**Issue by mufeng9891** [1em0nsOft/LemonHello4Android#11]
08-30 11:26:07.850 7875-7875/com.bxd.crowdsource E/MtaSDK.CaughtExp: java.lang.IllegalArgumentException: View=DecorView@873b47c[] not attached to window manager
                                                                         at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:520)
                                                                         at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:413)
                                                                         at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:206)
                                                                         at android.app.Dialog.dismissDialog(Dialog.java:495)
                                                                         at android.app.Dialog.dismiss(Dialog.java:478)
                                                                         at net.lemonsoft.lemonhello.LemonHelloView$3.run(LemonHelloView.java:295)
                                                                         at android.os.Handler.handleCallback(Handler.java:808)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                         at android.os.Looper.loop(Looper.java:166)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7425)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by yinfang** [comment]
在按钮回调中关闭当前界面需要添加延时，
 TimerTask task = new TimerTask() {
                                    @Override
                                    public void run() {
                                        finish();
                                        overridePendingTransition(-1, -1);
                                    }
                                };
                                if (mTimer == null) {
                                    mTimer = new Timer();
                                }
                                //秒后执行TimeTask的run方法
                                mTimer.schedule(task, 500);
